# Generated by Django 3.0.4 on 2021-05-09 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
        ('House', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Seller.Seller'),
            preserve_default=False,
        ),
    ]
